### ISSUE TITLE
目前如果手动修改了image name，rhino run 的时候会报错

### ISSUE THREAD

**Issue by LI-Mingyu** [OpenRHINO/RHINO-CLI#37]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/20229719/220659936-8f5b98d5-cfe7-43aa-8043-e13d872e9c19.png">
不知道这个应不应该算是一个 issue ？

**Comment by chichi321** [comment]
目前build时候给可执行文件命名是按照给定的镜像命名的，但是如果一个镜像今后只包含一个应用的话，可以将编译出的可执行文件名称统一（比如都叫func）就可以解决这个问题
